# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""
  DOCKER_BUILDKIT: 1
  USE_NEWER_NIX: 1

steps:
 - label: update auto release/pre-release
   commands:
   - mkdir binaries
   - mkdir arm-binaries
   - mkdir binaries/docker
   - mkdir arm-binaries/docker
   - nix develop .#autorelease -c ./scripts/autorelease.sh
   branches: pasqu4le/tmp-arm-sign
