# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""
  DOCKER_BUILDKIT: 1
  USE_NEWER_NIX: 1

steps:
 # We need to sign commits that update brew formulae separately
 - label: Sign formulae update commits
   if: build.branch =~ /^auto\/update-brew-formulae-.*/
   commands:
   - nix develop .#buildkite
       --command './scripts/sign-commits.sh'
 # To avoid race-conditions for the gpg key between jobs which sometimes leads to weird errors
 - wait

 - label: build-via-docker
   # this step is used as a dependency, so we're defining 'key' explicitely
   key: build-via-docker
   commands:
   - eval "$SET_VERSION"
   - cd docker
   - ./docker-static-build.sh
   artifact_paths:
     - ./docker/octez-*
   only_changes: &static_binaries_changes_regexes
   - docker/build/.*.sh
   - docker/build/Dockerfile
   - docker/docker-static-build.sh
   - meta.json
   - protocols.json

 - label: build-arm-via-docker
   # this step is used as a dependency, so we're defining 'key' explicitely
   key: build-arm-via-docker
   commands:
   - eval "$SET_VERSION"
   - cd docker
   - ./docker-static-build.sh
   - >
     for f in ./octez-*; do
       mv "\$f" "\$f-arm64"
     done
   artifact_paths:
     - ./docker/octez-*
   agents:
     queue: "arm64-darwin"
   only_changes: *static_binaries_changes_regexes

 - label: create auto release/pre-release
   key: auto-release
   commands:
   - mkdir binaries
   - mkdir arm-binaries
   - buildkite-agent artifact download "docker/*" binaries --step "build-via-docker"
   - buildkite-agent artifact download "docker/*" arm-binaries --step "build-arm-via-docker"
   - ls binaries
   - nix develop .#autorelease -c ./scripts/autorelease.sh "$BUILDKITE_MESSAGE"
   depends_on:
    - "build-via-docker"
    - "build-arm-via-docker"
   only_changes:
   - scripts/autorelease.sh
   - scripts/shell.nix
   # files from 'nix/' directory are used in the autorelease script
   - nix/.*
   - tezos-release.nix
   - release.nix
