# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""
  DOCKER_BUILDKIT: 1
  USE_NEWER_NIX: 1

steps:
 # We need to sign commits that update brew formulae separately
 - label: Sign formulae update commits
   if: build.branch =~ /^auto\/update-brew-formulae-.*/
   commands:
   - nix develop .#buildkite
       --command './scripts/sign-commits.sh'
 # To avoid race-conditions for the gpg key between jobs which sometimes leads to weird errors
 - wait

 - label: Build Monterey x86_64 bottles
   key: build-bottles-monterey-x86_64
   agents:
     queue: "x86_64-rosetta-darwin"
   commands:
   - nix develop .#autorelease-macos -c ./scripts/build-all-bottles.sh "monterey"
   artifact_paths:
     - '*.bottle.*'
   retry:
     automatic:
       limit: 1

 - label: Build Monterey arm64 bottles
   key: build-bottles-monterey-arm64
   agents:
     queue: "arm64-darwin"
   commands:
   - nix develop .#autorelease-macos -c ./scripts/build-all-bottles.sh "arm64_monterey"
   artifact_paths:
     - '*.bottle.*'
   retry:
     automatic:
       limit: 1

 # We use the tag that triggered the pipeline here.
 # However, this requires that the tag and the release name are the same, which
 # in practice it's always the case in this repo.
 - label: Add Monterey bottle hashes to formulae
   depends_on:
   - "build-bottles-monterey-arm64"
   - "build-bottles-monterey-x86_64"
   commands:
   - mkdir -p "Monterey"
   - nix develop .#buildkite -c gh release download "$BUILDKITE_TAG" -D "Monterey/" -p "*monterey.bottle.tar.gz"
   - nix develop .#autorelease -c ./scripts/sync-bottle-hashes.sh "$BUILDKITE_TAG" "Monterey"
