# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""
  DOCKER_BUILDKIT: 1
  USE_NEWER_NIX: 1

steps:
 - label: build-via-docker
   # this step is used as a dependency, so we're defining 'key' explicitely
   key: build-via-docker
   commands:
   - eval "$SET_VERSION"
   - cd docker
   - OCTEZ_EXECUTABLES=octez-node ./docker-static-build.sh
   artifact_paths:
     - ./docker/octez-*
   agents:
     queue: "docker"
   only_changes: &static_binaries_changes_regexes
   - docker/build/.*.sh
   - docker/build/Dockerfile
   - docker/docker-static-build.sh
   - meta.json
   - protocols.json
