# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""
  DOCKER_BUILDKIT: 1
  USE_NEWER_NIX: 1

steps:
 - label: Build fedora source packages
   key: build-fedora-source-packages
   if: build.branch == "pasqu4le/tmp"
   agents:
     queue: "docker"
   commands:
   - eval "$SET_VERSION"
   - nix develop .#docker-tezos-packages -c ./docker/build/fedora/build.py --type source -p tezos-baking
   artifact_paths:
     - ./out/*

 - label: Sign fedora source packages
   if: build.branch == "pasqu4le/tmp"
   depends_on:
   - "build-fedora-source-packages"
   key: sign-fedora-source-packages
   commands:
   - eval "$SET_VERSION"
   - buildkite-agent artifact download "out/*" . --step build-fedora-source-packages
   - nix develop .#docker-tezos-packages -c ./docker/build/fedora/sign.py -d out -i 'Serokell <tezos-packaging@serokell.io>'
   artifact_paths:
     - ./out/*

 - label: Publish fedora native packages
   if: build.branch == "pasqu4le/tmp"
   depends_on:
   - "sign-fedora-source-packages"
   commands:
   - eval "$SET_VERSION"
   - buildkite-agent artifact download "out/*" . --step sign-fedora-source-packages
   - nix develop .#buildkite -c ./docker/build/fedora/upload.py -d out
