# SPDX-FileCopyrightText: 2020 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: LicenseRef-MIT-TQ

FROM fedora:32
RUN dnf update -y
RUN dnf install -y libev-devel gmp-devel hidapi-devel libffi-devel m4 perl pkg-config \
  rpmdevtools python3 wget opam rsync which cargo
ENV USER dockerbuilder
RUN useradd dockerbuilder && mkdir /mavryk-packaging
ENV HOME /mavryk-packaging
COPY meta.json /mavryk-packaging/meta.json
COPY protocols.json /mavryk-packaging/protocols.json
WORKDIR /mavryk-packaging/docker
ENV OPAMROOT "/mavryk-packaging/docker/opamroot"
RUN opam init --bare --yes --disable-sandboxing
RUN opam switch create ocaml-base-compiler.4.09.1
RUN opam switch set ocaml-base-compiler.4.09.1
RUN opam install opam-bundle=0.4 --yes
COPY docker/package/*.py /mavryk-packaging/docker/package/
COPY docker/package/defaults /mavryk-packaging/docker/package/defaults
COPY docker/package/scripts /mavryk-packaging/docker/package/scripts
ENTRYPOINT ["python3", "-m", "package.package_generator"]
